### ISSUE TITLE
Erro docker build: unknown flag: --secret

### ISSUE THREAD

**Issue by labanca** [splor-mg/volumes-docker#30]
No docker version 25.0.2, build 29cf629 ao executar o comando 

`make image=ploa2025 relatorios=v0.7.59 execucao=v0.5.22 reest=v0.2.6` 

o seguinte erro acontece:

```
docker build \
    --tag volumes:ploa2025 \
    --secret id=secret,src=.env \
    --build-arg relatorios_version=v0.7.59 \
    --build-arg execucao_version=v0.5.22 \
    --build-arg reest_version=v0.2.6 \
    .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

unknown flag: --secret
See 'docker build --help'.
make: *** [Makefile:4: build] Error 125

```

**Comment by fjuniorr** [comment]
@labanca no meu pac usar `docker buildx build` para fazer build da imagem funcionou.

Dá uma olhada se você consegue fazer build no windows. 

Eu também alterei as [instruções](https://github.com/splor-mg/volumes-docker/commit/3d882ba1ec39a8ddf6ace20eced96d7d01609fbc) do README.md para que a publicação seja na conta da [splormg](https://hub.docker.com/u/splormg) no dockerhub e não na minha conta pessoal. Então faz o teste se você consegue publicar lá também.

Com esse issue finalizado a gente faz as alterações nos projetos da LOA pra usar as novas imagens e ver se tudo continua igual.

**Comment by labanca** [comment]
No Windows o `make build` não funcionava devido ao comando estar formatado em múltiplas linhas, o que foi corrigido em https://github.com/splor-mg/volumes-docker/commit/83b0046652c61ae142ae42dacfe12a73c9226673

Gerei novamente os volumes da LOA e rodei os testes de diff de PDF e passaram todos (https://github.com/splor-mg/volumes-loa/commit/9c1eee3afe5b7f08ba4ba6c64a7962c286523d71):

![Image](https://github.com/user-attachments/assets/b40f1dc0-5e90-417c-95e6-47b3ff179a39)
